/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SurveyRouteImport } from './routes/survey'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PublicRouteRouteImport } from './routes/_public/route'
import { Route as PublicIndexRouteImport } from './routes/_public/index'
import { Route as PublicAuthenticatedRouteImport } from './routes/_public/_authenticated'
import { Route as errors503RouteImport } from './routes/(errors)/503'
import { Route as errors500RouteImport } from './routes/(errors)/500'
import { Route as errors404RouteImport } from './routes/(errors)/404'
import { Route as errors403RouteImport } from './routes/(errors)/403'
import { Route as errors401RouteImport } from './routes/(errors)/401'
import { Route as authSignInRouteImport } from './routes/(auth)/sign-in'
import { Route as adminAdminRouteImport } from './routes/(admin)/admin'
import { Route as adminAdminIndexRouteImport } from './routes/(admin)/admin/index'
import { Route as PublicAuthenticatedWatchlistsIndexRouteImport } from './routes/_public/_authenticated/watchlists/index'
import { Route as PublicAuthenticatedPortfolioIndexRouteImport } from './routes/_public/_authenticated/portfolio/index'
import { Route as PublicAuthenticatedAnalysisIndexRouteImport } from './routes/_public/_authenticated/analysis/index'
import { Route as PublicStocksMarketTickerRouteImport } from './routes/_public/stocks.$market.$ticker'

const SurveyRoute = SurveyRouteImport.update({
  id: '/survey',
  path: '/survey',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicRouteRoute = PublicRouteRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicAuthenticatedRoute = PublicAuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => PublicRouteRoute,
} as any)
const errors503Route = errors503RouteImport.update({
  id: '/(errors)/503',
  path: '/503',
  getParentRoute: () => rootRouteImport,
} as any)
const errors500Route = errors500RouteImport.update({
  id: '/(errors)/500',
  path: '/500',
  getParentRoute: () => rootRouteImport,
} as any)
const errors404Route = errors404RouteImport.update({
  id: '/(errors)/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const errors403Route = errors403RouteImport.update({
  id: '/(errors)/403',
  path: '/403',
  getParentRoute: () => rootRouteImport,
} as any)
const errors401Route = errors401RouteImport.update({
  id: '/(errors)/401',
  path: '/401',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignInRoute = authSignInRouteImport.update({
  id: '/(auth)/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const adminAdminRoute = adminAdminRouteImport.update({
  id: '/(admin)/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const adminAdminIndexRoute = adminAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => adminAdminRoute,
} as any)
const PublicAuthenticatedWatchlistsIndexRoute =
  PublicAuthenticatedWatchlistsIndexRouteImport.update({
    id: '/watchlists/',
    path: '/watchlists/',
    getParentRoute: () => PublicAuthenticatedRoute,
  } as any)
const PublicAuthenticatedPortfolioIndexRoute =
  PublicAuthenticatedPortfolioIndexRouteImport.update({
    id: '/portfolio/',
    path: '/portfolio/',
    getParentRoute: () => PublicAuthenticatedRoute,
  } as any)
const PublicAuthenticatedAnalysisIndexRoute =
  PublicAuthenticatedAnalysisIndexRouteImport.update({
    id: '/analysis/',
    path: '/analysis/',
    getParentRoute: () => PublicAuthenticatedRoute,
  } as any)
const PublicStocksMarketTickerRoute =
  PublicStocksMarketTickerRouteImport.update({
    id: '/stocks/$market/$ticker',
    path: '/stocks/$market/$ticker',
    getParentRoute: () => PublicRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/profile': typeof ProfileRoute
  '/survey': typeof SurveyRoute
  '/admin': typeof adminAdminRouteWithChildren
  '/sign-in': typeof authSignInRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/': typeof PublicIndexRoute
  '/admin/': typeof adminAdminIndexRoute
  '/stocks/$market/$ticker': typeof PublicStocksMarketTickerRoute
  '/analysis': typeof PublicAuthenticatedAnalysisIndexRoute
  '/portfolio': typeof PublicAuthenticatedPortfolioIndexRoute
  '/watchlists': typeof PublicAuthenticatedWatchlistsIndexRoute
}
export interface FileRoutesByTo {
  '/profile': typeof ProfileRoute
  '/survey': typeof SurveyRoute
  '/sign-in': typeof authSignInRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/': typeof PublicIndexRoute
  '/admin': typeof adminAdminIndexRoute
  '/stocks/$market/$ticker': typeof PublicStocksMarketTickerRoute
  '/analysis': typeof PublicAuthenticatedAnalysisIndexRoute
  '/portfolio': typeof PublicAuthenticatedPortfolioIndexRoute
  '/watchlists': typeof PublicAuthenticatedWatchlistsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_public': typeof PublicRouteRouteWithChildren
  '/profile': typeof ProfileRoute
  '/survey': typeof SurveyRoute
  '/(admin)/admin': typeof adminAdminRouteWithChildren
  '/(auth)/sign-in': typeof authSignInRoute
  '/(errors)/401': typeof errors401Route
  '/(errors)/403': typeof errors403Route
  '/(errors)/404': typeof errors404Route
  '/(errors)/500': typeof errors500Route
  '/(errors)/503': typeof errors503Route
  '/_public/_authenticated': typeof PublicAuthenticatedRouteWithChildren
  '/_public/': typeof PublicIndexRoute
  '/(admin)/admin/': typeof adminAdminIndexRoute
  '/_public/stocks/$market/$ticker': typeof PublicStocksMarketTickerRoute
  '/_public/_authenticated/analysis/': typeof PublicAuthenticatedAnalysisIndexRoute
  '/_public/_authenticated/portfolio/': typeof PublicAuthenticatedPortfolioIndexRoute
  '/_public/_authenticated/watchlists/': typeof PublicAuthenticatedWatchlistsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/profile'
    | '/survey'
    | '/admin'
    | '/sign-in'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/'
    | '/admin/'
    | '/stocks/$market/$ticker'
    | '/analysis'
    | '/portfolio'
    | '/watchlists'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/profile'
    | '/survey'
    | '/sign-in'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/'
    | '/admin'
    | '/stocks/$market/$ticker'
    | '/analysis'
    | '/portfolio'
    | '/watchlists'
  id:
    | '__root__'
    | '/_public'
    | '/profile'
    | '/survey'
    | '/(admin)/admin'
    | '/(auth)/sign-in'
    | '/(errors)/401'
    | '/(errors)/403'
    | '/(errors)/404'
    | '/(errors)/500'
    | '/(errors)/503'
    | '/_public/_authenticated'
    | '/_public/'
    | '/(admin)/admin/'
    | '/_public/stocks/$market/$ticker'
    | '/_public/_authenticated/analysis/'
    | '/_public/_authenticated/portfolio/'
    | '/_public/_authenticated/watchlists/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  PublicRouteRoute: typeof PublicRouteRouteWithChildren
  ProfileRoute: typeof ProfileRoute
  SurveyRoute: typeof SurveyRoute
  adminAdminRoute: typeof adminAdminRouteWithChildren
  authSignInRoute: typeof authSignInRoute
  errors401Route: typeof errors401Route
  errors403Route: typeof errors403Route
  errors404Route: typeof errors404Route
  errors500Route: typeof errors500Route
  errors503Route: typeof errors503Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/survey': {
      id: '/survey'
      path: '/survey'
      fullPath: '/survey'
      preLoaderRoute: typeof SurveyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof PublicRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/_authenticated': {
      id: '/_public/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof PublicAuthenticatedRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/(errors)/503': {
      id: '/(errors)/503'
      path: '/503'
      fullPath: '/503'
      preLoaderRoute: typeof errors503RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/500': {
      id: '/(errors)/500'
      path: '/500'
      fullPath: '/500'
      preLoaderRoute: typeof errors500RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/404': {
      id: '/(errors)/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof errors404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/403': {
      id: '/(errors)/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof errors403RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/401': {
      id: '/(errors)/401'
      path: '/401'
      fullPath: '/401'
      preLoaderRoute: typeof errors401RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(admin)/admin': {
      id: '/(admin)/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof adminAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(admin)/admin/': {
      id: '/(admin)/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof adminAdminIndexRouteImport
      parentRoute: typeof adminAdminRoute
    }
    '/_public/_authenticated/watchlists/': {
      id: '/_public/_authenticated/watchlists/'
      path: '/watchlists'
      fullPath: '/watchlists'
      preLoaderRoute: typeof PublicAuthenticatedWatchlistsIndexRouteImport
      parentRoute: typeof PublicAuthenticatedRoute
    }
    '/_public/_authenticated/portfolio/': {
      id: '/_public/_authenticated/portfolio/'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PublicAuthenticatedPortfolioIndexRouteImport
      parentRoute: typeof PublicAuthenticatedRoute
    }
    '/_public/_authenticated/analysis/': {
      id: '/_public/_authenticated/analysis/'
      path: '/analysis'
      fullPath: '/analysis'
      preLoaderRoute: typeof PublicAuthenticatedAnalysisIndexRouteImport
      parentRoute: typeof PublicAuthenticatedRoute
    }
    '/_public/stocks/$market/$ticker': {
      id: '/_public/stocks/$market/$ticker'
      path: '/stocks/$market/$ticker'
      fullPath: '/stocks/$market/$ticker'
      preLoaderRoute: typeof PublicStocksMarketTickerRouteImport
      parentRoute: typeof PublicRouteRoute
    }
  }
}

interface PublicAuthenticatedRouteChildren {
  PublicAuthenticatedAnalysisIndexRoute: typeof PublicAuthenticatedAnalysisIndexRoute
  PublicAuthenticatedPortfolioIndexRoute: typeof PublicAuthenticatedPortfolioIndexRoute
  PublicAuthenticatedWatchlistsIndexRoute: typeof PublicAuthenticatedWatchlistsIndexRoute
}

const PublicAuthenticatedRouteChildren: PublicAuthenticatedRouteChildren = {
  PublicAuthenticatedAnalysisIndexRoute: PublicAuthenticatedAnalysisIndexRoute,
  PublicAuthenticatedPortfolioIndexRoute:
    PublicAuthenticatedPortfolioIndexRoute,
  PublicAuthenticatedWatchlistsIndexRoute:
    PublicAuthenticatedWatchlistsIndexRoute,
}

const PublicAuthenticatedRouteWithChildren =
  PublicAuthenticatedRoute._addFileChildren(PublicAuthenticatedRouteChildren)

interface PublicRouteRouteChildren {
  PublicAuthenticatedRoute: typeof PublicAuthenticatedRouteWithChildren
  PublicIndexRoute: typeof PublicIndexRoute
  PublicStocksMarketTickerRoute: typeof PublicStocksMarketTickerRoute
}

const PublicRouteRouteChildren: PublicRouteRouteChildren = {
  PublicAuthenticatedRoute: PublicAuthenticatedRouteWithChildren,
  PublicIndexRoute: PublicIndexRoute,
  PublicStocksMarketTickerRoute: PublicStocksMarketTickerRoute,
}

const PublicRouteRouteWithChildren = PublicRouteRoute._addFileChildren(
  PublicRouteRouteChildren,
)

interface adminAdminRouteChildren {
  adminAdminIndexRoute: typeof adminAdminIndexRoute
}

const adminAdminRouteChildren: adminAdminRouteChildren = {
  adminAdminIndexRoute: adminAdminIndexRoute,
}

const adminAdminRouteWithChildren = adminAdminRoute._addFileChildren(
  adminAdminRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  PublicRouteRoute: PublicRouteRouteWithChildren,
  ProfileRoute: ProfileRoute,
  SurveyRoute: SurveyRoute,
  adminAdminRoute: adminAdminRouteWithChildren,
  authSignInRoute: authSignInRoute,
  errors401Route: errors401Route,
  errors403Route: errors403Route,
  errors404Route: errors404Route,
  errors500Route: errors500Route,
  errors503Route: errors503Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
