spring:
  datasource:
    url: jdbc:mysql://localhost:3306/appdb?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID:dev-client}
            client-secret: ${GOOGLE_CLIENT_SECRET:dev-secret}
            scope: openid,profile,email
        provider:
          google:
            issuer-uri: https://accounts.google.com

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace