spring:
  profiles:
    default: dev
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
  mvc:
    problemdetails:
      enabled: true
  jpa:
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
  message:
    basename: messages
    encoding: UTF-8
  output:
    ansi:
      enabled: always

server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      enabled: ture
      force: true
  forward-headers-strategy: native
  timezone: Asia/Seoul

management:
  endpoints:
    web:
      exposure:
        include: health, info